name: create-release
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  Release-Windows:
    name: Creating a Release on Github
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          npm install
          npm run package
      - name: Delete Older Releases
        uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          keep_latest: 0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Github Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: release
          name: ${{ github.event.head_commit.message }}
          body: |
            Commit Message: `${{ github.event.head_commit.message }}`
            Built time: `${{ github.event.head_commit.timestamp }}`
          draft: false
          prerelease: false
          files: |
            ./release/build/*.exe
            ./release/build/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
